name: Sowo CI
on: [push, pull_request]

jobs:
  build_examples:
    name: Build examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.13.8'
      
      - name: build examples
        run: make examples
      